version: '3.8'

services:
  redis_db:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/databases/redis/data:/data
  mongo_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./docker/databases/mongo/data/db:/data/db
      - ./docker/databases/mongo/data/configdb:/data/configdb
  postgres_db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/databases/postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root
