version: '3.8'

services:
  redis_db:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - default
      - shared-network
    volumes:
      - ./docker/databases/redis/data:/data
  mongo_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    networks:
      - default
      - shared-network
    volumes:
      - ./docker/databases/mongo/data/db:/data/db
      - ./docker/databases/mongo/data/configdb:/data/configdb
      - ./docker/databases/mongo/init:/docker-entrypoint-initdb.d
  postgres_db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./docker/databases/postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    networks:
      - default
      - shared-network
    hostname: postgres
    user: root

networks:
  shared-network:
    external: true
